select * from access_policy;
select * from account;
select * from account_roles;
select * from api_key;
select * from api_key_log;
select * from billing_log;
select * from flyway_schema_history;
select * from scope;
select * from security_log;